### ISSUE TITLE
"final int COLUMN_NUMBER = 0;" inside while

### ISSUE THREAD

**Issue by mbork** [pchmielowski/ContextAwareTodoList#1]
I don't know much about Java (I'm learning it while taking part in the contest), so maybe the compiler optimizes this anyway, but why is "final int COLUMN_NUMBER = 0;" inside the while loop (in TaskList.java)???

**Comment by pchmielowski** [comment]
Look at:

```
public Cursor getTaskNames() {
        return getReadableDatabase().query(DATABASE,
                new String[]{COLUMN_TASK},
                null, null, null, null, null);
```

`{COLUMN_TASK}` - this is a list of columns to be retrieved from DB. Now it contains one element, therefore one column will be retrieved. `COLUMN_NUMBER` means first (in this case the only one) column in query answer.
